### ISSUE TITLE
Can I use 'One' mode with different label as 'Many' mode?

### ISSUE THREAD

**Issue by unclechu** [hashchange/backbone.select#13]
Can I work with default label using Backbone.Select.One for collection and with custom label using Backbone.Select.Many for single collection?

**Comment by unclechu** [comment]
As I can see I should use `{ exclusive: true }` and work with collection property as hash map of selected models, it's only way to do it?

**Comment by hashchange** [comment]
I'm not sure I have understood you correctly, but I figured you want to use a just a single collection, and then have Select.One behaviour for one label and Select.Many behaviour for another? 

In that case, no, that can't be done without a workaround. You can apply either of the mixins to a single collection, but not both. 

One solution would be to do it with one collection only, and apply the Select.Many mixin to it. Then you can use two labels, and make sure `select` is always called with the `exclusive` option for one of the labels.

Another approach is to create two collections, rather than one, with the same set of models. One collection gets the Select.One mixin; the other collection gets the Select.Many mixin and a different default label. You'll also need to [ignore that second label][1] in the Select.One collection.

Perhaps you'll find some additional inspiration in these two demos:

- Focusing on one selected item in a Select.Many collection, using custom labels: [JSBin][demo-focus-with-label-jsbin], [Codepen][demo-focus-with-label-codepen]
- Focusing on one selected item in a Select.Many collection, using the `exclusive` option: [JSBin][demo-focus-with-exclusive-jsbin], [Codepen][demo-focus-with-exclusive-codepen]

[1]: https://github.com/hashchange/backbone.select/tree/1.5.3#the-ignorelabel-setup-option
[demo-focus-with-label-jsbin]: http://jsbin.com/soduyi/1/edit?js,output "Backbone.Select: Focusing on one selected item in a Select.Many collection, using custom labels (AMD)"
[demo-focus-with-label-codepen]: http://codepen.io/hashchange/pen/wKJzWE "Backbone.Select: Focusing on one selected item in a Select.Many collection, using custom labels (AMD)"
[demo-focus-with-exclusive-jsbin]: http://jsbin.com/colulo/1/edit?js,output "Backbone.Select: Focusing on one selected item in a Select.Many collection, using the `exclusive` option (AMD)"
[demo-focus-with-exclusive-codepen]: http://codepen.io/hashchange/pen/QjpKGo "Backbone.Select: Focusing on one selected item in a Select.Many collection, using the `exclusive` option (AMD)"

**Comment by unclechu** [comment]
@hashchange thank you for the answer. `exclusive` option with Select.Many mixin solves my issue.
