### ISSUE TITLE
collections/models with more then one "selected state"

### ISSUE THREAD

**Issue by justinshea** [hashchange/backbone.select#9]
Hi There,

Thanks for a nice mix in. I've am wondering if it can cover a few usage cases I am not clear about after reading documentation and testing a little bit. Please consider the following cases:

Scenario 1:
A collection where we want to track selected state for a model that has been "starred" and a model that has been "up voted" (tracking two separate selected states for models in the same collection).

Scenario 2:
A model is passed between "collection a" which uses "select one" mix in and "collection b" that uses "select many" mix in. The model had previously been selected in collection a and we want to keep it's selected state until another model is selected or that model is deselected. Additionally, we want to make the model available to be one of the many selected in collection b without affecting it's select one status from "collection a".

Thanks for considering.
Justin

**Comment by hashchange** [comment]
Hi Justin,

it's funny you should say that because I have run into the exact same limitations recently, and I am working on this right now. You can see a solution emerging in the feature-label branch. Your scenario 1 is essentially done, but still needs unit tests and documentation. Scenario 2 is already in the works. I don't really want to commit myself, but it would not be unreasonable for you to expect a build sometime next week - perhaps as a beta release.

Cheers,

Michael

**Comment by justinshea** [comment]
awesome! I like the label concept...

**Comment by hashchange** [comment]
Has landed in 1.4.0. Enjoy :)

**Comment by justinshea** [comment]
hat tip. can't wait to get into it...
